### ISSUE TITLE
⚠️ Minecraft has degraded performance

### ISSUE THREAD

**Issue by auggeeo** [CoopPlayzz/Webstatus-games#349]
In [`01d22dd`](https://github.com/CoopPlayzz/Webstatus-games/commit/01d22ddd69c5172cbbe8044b404b9761972b7779
), Minecraft (https://www.minecraft.net) experienced **degraded performance**:
- HTTP code: 200
- Response time: 929 ms

**Comment by CoopPlayzz** [comment]
**Resolved:** Minecraft performance has improved in [`3f0710e`](https://github.com/CoopPlayzz/Webstatus-games/commit/3f0710e318b2c96fe85013a1fe24ea62ef2c7746
).
